name: Vault # must be 'Vault', because other plugins would not load
# name: Vaulty
author: lightPlugins
version: 1.0.0
main: io.lightplugins.vaulty.Vaulty
api-version: 1.13
depend: []
softdepend: []
loadbefore: []
libraries: []
load: startup
commands:
  vaulty-info:
    description: The root command for administrated things
  vaulty-convert:
    description: Convert economy accounts from A to B